# Рабочая тетрадь № 2

## 1.1. Теоретический материал – Библиотека NumPy
NumPy (**Num**erical**Py**thon) - это библиотека Python с открытым исходным кодом, которая используется практически во всех областях науки и техники. Это универсальный стандарт для работы с числовыми данными в Python. 
  
Если у вас уже есть Python, вы можете установить NumPy с помощью командной строки:  
`pip install numpy`
    
Чтобы начать использовать NumPy необходимо импортировать соответствующую библиотеку:  
`import numpy as np`
    
Основным объектом NumPy является однородный многомерный массив (в numpy называется numpy.ndarray). Это многомерный массив элементов (обычно чисел), одного типа.

Наиболее важные атрибуты объектов ndarray:  
**ndarray.ndim** - число измерений (чаще их называют "оси") массива.
  
**ndarray.shape** - размеры массива, его форма. Это кортеж натуральных чисел, показывающий длину массива по каждой оси. Для матрицы из n строк и m столбов, shape будет (n,m). Число элементов кортежа shape равно ndim.
  
**ndarray.size** - количество элементов массива. Очевидно, равно произведению всех элементов атрибута shape.
  
**ndarray.dtype** - объект, описывающий тип элементов массива. Можно определить dtype, используя стандартные типы данных Python. NumPy здесь предоставляет целый букет возможностей, как встроенных, например: bool_, character, int8, int16, int32, int64, float8, float16, float32, float64, complex64, object_, так и возможность определить собственные типы данных, в том числе и составные.
  
**ndarray.itemsize** - размер каждого элемента массива в байтах.
**ndarray.data** - буфер, содержащий фактические элементы массива. Обычно не нужно использовать этот атрибут, так как обращаться к элементам массива проще всего с помощью индексов.
  
Подробнее о массивах в NumPy можно найти в официальной документации https://numpy.org/doc/stable/user/absolute_beginners.html

### 1.2.1 Пример
#### Задача: создать массив 5x2. Вывести все значения массива, значение элемента с индексом (3,1) и второй столбец. Индексация начинается с нуля

In [71]:
import numpy as np

x = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


### 1.2.2 Пример
#### Задача: выполнить следующее:
1. Создать вектор (одномерный массив) размера 10, заполненный нулями
2. Создать вектор размера 10, заполненный единицами
3. Создать вектор размера 10, заполненный заданным числом
4. Создать вектор со значениями от 10 до 19

In [72]:
import numpy as np

a = np.zeros(10)
b = np.ones(10)
c = np.full(10, 5)
d = np.arange(10, 20)

print(a, "\n", b, "\n", c, "\n", d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19]


### 1.2.3 Пример
#### Задача: создать массив 10x10 со случайными значениями, найти минимум, максимум и среднее значение

In [73]:
Z = np.random.random((10,10))
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean()
print(Zmin, Zmax, Zmean)

0.0020267823961440667 0.9959014413864888 0.5215796288852864


### 1.2.4 Пример
#### Задача: задать матрицу размерности 5 на 5 и поменять 2 строки в матрице местами

In [74]:
A = np.arange(25).reshape(5, 5)
A[[0, 1]] = A[[1, 0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


### 1.2.5 Пример
#### Задача: выяснить результат следующих выражений:
```
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [75]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


### 1.2.6 Пример
#### Задача: отсортировать массив

In [76]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


### 1.3.1 Задание
#### Задача: создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами

In [77]:
import numpy as np

matrix = np.zeros((8, 8), dtype=int)

matrix[1::2, ::2] = 1  # чётные строки -> 1 на чётных столбцах
matrix[::2, 1::2] = 1  # нечётные строки -> 1 на нечётных столбцах

print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 1.3.2 Задание
#### Задача: создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания необходимо использовать функцию arange

In [78]:
import numpy as np

array = np.arange(5).reshape(1, -1) + np.arange(5).reshape(-1, 1)

new_array = (array - array.min()) % 5

print(new_array)

[[0 1 2 3 4]
 [1 2 3 4 0]
 [2 3 4 0 1]
 [3 4 0 1 2]
 [4 0 1 2 3]]


### 1.3.3 Задание
#### Задача: создать массив 3x3x3 со случайными значениями

In [79]:
import numpy as np

array = np.random.randint(0, 10, size=(3, 3, 3))

print(array)


[[[5 6 7]
  [2 5 6]
  [8 0 1]]

 [[3 6 5]
  [5 8 1]
  [8 0 7]]

 [[6 7 8]
  [7 0 3]
  [9 9 1]]]


### 1.3.4 Задание
#### Задача: создать матрицу с 0 внутри, и 1 на границах

In [80]:
import numpy as np

matrix = np.zeros((5, 5), dtype=int)

matrix[0, :] = 1  # верхняя граница
matrix[-1, :] = 1  # нижняя граница
matrix[:, 0] = 1  # левая граница
matrix[:, -1] = 1  # правая граница

print(matrix)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


### 1.3.5 Задание
#### Задача: создайте массив и отсортируйте его по убыванию

In [81]:
import numpy as np

arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5])

sorted_arr = np.sort(arr)[::-1]

print(sorted_arr)

[9 6 5 5 4 3 2 1 1]


### 1.3.6 Задание
#### Задача: создайте матрицу, выведите ее форму, размер и размерность

In [82]:
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Форма матрицы:", matrix.shape)
print("Размер матрицы:", matrix.size)
print("Размерность матрицы:", matrix.ndim)

Форма матрицы: (3, 3)
Размер матрицы: 9
Размерность матрицы: 2


## 2.1. Теоретический материал – Библиотека Pandas
Первым шагом в любом начинании в области машинного обучения является введение исходных данных в систему. Исходные данные могут вводиться вручную, содержаться в файле или храниться в интернете в каком-либо формате. Кроме того, часто требуется получить данные из нескольких источников.  

*Библиотека pandas* – это удобный и быстрый инструмент для работы с данными, обладающий большим функционалом. Если очень кратко, то *pandas* – это библиотека, которая предоставляет очень удобные с точки зрения использования инструменты для хранения данных и работе с ними.  

*Библиотека pandas* присутствует в стандартной поставке Anaconda.
Если же ее там нет, то его можно установить отдельно. Для этого введите
командной строке:  
`pip install pandas`  

Для импорта библиотеки используйте команду:  
`import pandas as pd`  

Библиотека pandas предоставляет две ключевые структуры данных: Series и DataFrame.  

**Series** – это одномерная структура данных, ее можно представить, как таблицу с одной строкой. С Series можно работать как с обычным массивом(обращаться по номеру индекса), и как с ассоциированным массивом, когда можно использовать ключ для доступа к элементам данных.  

**DataFrame** – это двумерная структура. Идейно она очень похожа на обычную таблицу, что выражается в способе ее создания и работе с ее элементами.

### 2.2.1 Пример
#### Создать Series из списка Python, словаря Python, и массива Numpy (установить буквенные метки для последнего)

In [83]:
import pandas as pd
import numpy as np

lst = [1, 2, 3, 4, 5]
d = {'a':1, 'b':2, 'c':3}
ndarr = np.array([1, 2, 3, 4, 5])

s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr, ['a', 'b', 'c', 'd', 'e'])

print(s1)
print(s2)
print(s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64


### 2.2.3 Пример
#### Задача: создайте новый фрейм данных

In [84]:
import pandas as pd

dataframe = pd.DataFrame()
dataframe['Имя'] = ['Джеки Джексон', 'Стивен Стивенсон']
dataframe['Возраст'] = [38, 25]
dataframe['Водитель'] = [True, False]
dataframe

Имя  Возраст  Водитель
0     Джеки Джексон       38      True
1  Стивен Стивенсон       25     False

### 2.2.4 Пример
#### Задача: загрузите фрейм данных по ссылке:
https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv

In [85]:
import pandas as pd

# Создать URL-адрес
url = 'https://raw.githubusercontent.com/rolandmueller/titanic/main/titanic3.csv'

# Загрузить данные
dataframe = pd.read_csv(url)

# Показать пять строк
dataframe.head(5)

pclass  survived                                             name     sex  \
0       1         1                    Allen, Miss. Elisabeth Walton  female   
1       1         1                   Allison, Master. Hudson Trevor    male   
2       1         0                     Allison, Miss. Helen Loraine  female   
3       1         0             Allison, Mr. Hudson Joshua Creighton    male   
4       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female   

       age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
0  29.0000      0      0   24160  211.3375       B5        S    2    NaN   
1   0.9167      1      2  113781  151.5500  C22 C26        S   11    NaN   
2   2.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
3  30.0000      1      2  113781  151.5500  C22 C26        S  NaN  135.0   
4  25.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON  
2  Montreal, PQ / Chesterville, ON  
3  Montreal, PQ / Chesterville, ON  
4  Montreal, PQ / Chesterville, ON

### 2.2.5 Пример
#### Задача: пронализировать характеристики фрейма данных

Одна из самых простых вещей, которые мы можем сделать после загрузки данных, – это взглянуть на первые несколько строк с помощью метода head. На последние строки можно посмотреть с помощью функции tail. Мы также можем взглянуть на количество строк и столбцов: dataframe.shape. Кроме того, используя метод describe, мы можем получить описательную статистику для любых числовых столбцов.

In [86]:
import pandas as pd

# Создать URL-адрес
url = 'https://raw.githubusercontent.com/rolandmueller/titanic/main/titanic3.csv'

# Загрузить данные
dataframe = pd.read_csv(url)

dataframe.head(2)

pclass  survived                            name     sex      age  sibsp  \
0       1         1   Allen, Miss. Elisabeth Walton  female  29.0000      0   
1       1         1  Allison, Master. Hudson Trevor    male   0.9167      1   

   parch  ticket      fare    cabin embarked boat  body  \
0      0   24160  211.3375       B5        S    2   NaN   
1      2  113781  151.5500  C22 C26        S   11   NaN   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON

In [87]:
dataframe.tail(3)

pclass  survived                       name   sex   age  sibsp  parch  \
1306       3         0  Zakarian, Mr. Mapriededer  male  26.5      0      0   
1307       3         0        Zakarian, Mr. Ortin  male  27.0      0      0   
1308       3         0         Zimmerman, Mr. Leo  male  29.0      0      0   

      ticket   fare cabin embarked boat   body home.dest  
1306    2656  7.225   NaN        C  NaN  304.0       NaN  
1307    2670  7.225   NaN        C  NaN    NaN       NaN  
1308  315082  7.875   NaN        S  NaN    NaN       NaN

In [88]:
dataframe.shape

(1309, 14)

In [89]:
dataframe.describe()

pclass     survived          age        sibsp        parch  \
count  1309.000000  1309.000000  1046.000000  1309.000000  1309.000000   
mean      2.294882     0.381971    29.881135     0.498854     0.385027   
std       0.837836     0.486055    14.413500     1.041658     0.865560   
min       1.000000     0.000000     0.166700     0.000000     0.000000   
25%       2.000000     0.000000    21.000000     0.000000     0.000000   
50%       3.000000     0.000000    28.000000     0.000000     0.000000   
75%       3.000000     1.000000    39.000000     1.000000     0.000000   
max       3.000000     1.000000    80.000000     8.000000     9.000000   

              fare        body  
count  1308.000000  121.000000  
mean     33.295479  160.809917  
std      51.758668   97.696922  
min       0.000000    1.000000  
25%       7.895800   72.000000  
50%      14.454200  155.000000  
75%      31.275000  256.000000  
max     512.329200  328.000000

### 2.2.6 Пример
#### Задача: выберите индивидуальные данные или срезы фрейма данных
  
Для выбора одной или нескольких строк, либо значений, можно использовать методы **1ос** или **iloc**

In [90]:
import pandas as pd

# Создать URL-адрес
url = 'https://raw.githubusercontent.com/rolandmueller/titanic/main/titanic3.csv'

# Загрузить данные
dataframe = pd.read_csv(url)

dataframe.iloc[1:4]

pclass  survived                                  name     sex      age  \
1       1         1        Allison, Master. Hudson Trevor    male   0.9167   
2       1         0          Allison, Miss. Helen Loraine  female   2.0000   
3       1         0  Allison, Mr. Hudson Joshua Creighton    male  30.0000   

   sibsp  parch  ticket    fare    cabin embarked boat   body  \
1      1      2  113781  151.55  C22 C26        S   11    NaN   
2      1      2  113781  151.55  C22 C26        S  NaN    NaN   
3      1      2  113781  151.55  C22 C26        S  NaN  135.0   

                         home.dest  
1  Montreal, PQ / Chesterville, ON  
2  Montreal, PQ / Chesterville, ON  
3  Montreal, PQ / Chesterville, ON

### 2.2.7 Пример
#### Задача: требуется отобрать строки фрейма данных на основе некоторого условия. Необходимо сформировать новый фрейм данных из пассажиров первого класса

In [91]:
import pandas as pd

# Создать URL-адрес
url = 'https://raw.githubusercontent.com/rolandmueller/titanic/main/titanic3.csv'

# Загрузить данные
dataframe = pd.read_csv(url)

dataframe[dataframe['pclass'] == 1].head(2)

pclass  survived                            name     sex      age  sibsp  \
0       1         1   Allen, Miss. Elisabeth Walton  female  29.0000      0   
1       1         1  Allison, Master. Hudson Trevor    male   0.9167      1   

   parch  ticket      fare    cabin embarked boat  body  \
0      0   24160  211.3375       B5        S    2   NaN   
1      2  113781  151.5500  C22 C26        S   11   NaN   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON

### 2.3.1 Задание
#### Задача: найдите евклидово расстояние между двумя Series (точками) a и b, не используя встроенную формулу

In [92]:
a = pd.Series([1, 2, 3])
b = pd.Series([4, 5, 6])

diff = (a - b)**2

sum_diffs = np.sum(diff)

# Находим квадратный корень из суммы квадратов разниц
dist = np.sqrt(sum_diffs)

print("Евклидово расстояние между точками a и b:", dist)

Евклидово расстояние между точками a и b: 5.196152422706632


### 2.3.2 Задание
#### Найдите в Интернете ссылку на любой csv файл и сформируйте из него фрейм данных (например, коллекцию фреймов данных можно найти здесь: https://github.com/akmand/datasets)

In [93]:
import pandas as pd

# Создать URL-адрес
url = 'https://raw.githubusercontent.com/akmand/datasets/main/adult.csv'

# Загрузить данные
dataframe = pd.read_csv(url)

# Показать пять строк
dataframe.head(5)

age         workclass  education_num      marital_status  \
0   39         State-gov             13       Never-married   
1   50  Self-emp-not-inc             13  Married-civ-spouse   
2   38           Private              9            Divorced   
3   53           Private              7  Married-civ-spouse   
4   28           Private             13  Married-civ-spouse   

          occupation   relationship   race  gender  hours_per_week  \
0       Adm-clerical  Not-in-family  White    Male              40   
1    Exec-managerial        Husband  White    Male              13   
2  Handlers-cleaners  Not-in-family  White    Male              40   
3  Handlers-cleaners        Husband  Other    Male              40   
4     Prof-specialty           Wife  Other  Female              40   

  native_country  capital income_status  
0  United-States     2174         <=50K  
1  United-States        0         <=50K  
2  United-States        0         <=50K  
3  United-States        0         <=50K  
4          Other        0         <=50K

### 2.3.3 Задание
#### Задача: Проделайте с получившемся из предыдущего задания фреймом данных те же действия, что и в примерах 2.2.5-2.2.7

In [94]:
#2.2.5 (1)
dataframe.head(2)

age         workclass  education_num      marital_status       occupation  \
0   39         State-gov             13       Never-married     Adm-clerical   
1   50  Self-emp-not-inc             13  Married-civ-spouse  Exec-managerial   

    relationship   race gender  hours_per_week native_country  capital  \
0  Not-in-family  White   Male              40  United-States     2174   
1        Husband  White   Male              13  United-States        0   

  income_status  
0         <=50K  
1         <=50K

In [95]:
#2.2.5 (2)
dataframe.tail(3)

age     workclass  education_num      marital_status       occupation  \
45219   38       Private             13  Married-civ-spouse   Prof-specialty   
45220   44       Private             13            Divorced     Adm-clerical   
45221   35  Self-emp-inc             13  Married-civ-spouse  Exec-managerial   

      relationship   race gender  hours_per_week native_country  capital  \
45219      Husband  White   Male              50  United-States        0   
45220    Own-child  Other   Male              40  United-States     5455   
45221      Husband  White   Male              60  United-States        0   

      income_status  
45219         <=50K  
45220         <=50K  
45221          >50K

In [96]:
#2.2.5 (3)
dataframe.shape

(45222, 12)

In [97]:
#2.2.5 (4)
dataframe.describe()

age  education_num  hours_per_week       capital
count  45222.000000   45222.000000    45222.000000  45222.000000
mean      38.547941      10.118460       40.938017   1012.834925
std       13.217870       2.552881       12.007508   7530.315380
min       17.000000       1.000000        1.000000  -4356.000000
25%       28.000000       9.000000       40.000000      0.000000
50%       37.000000      10.000000       40.000000      0.000000
75%       47.000000      13.000000       45.000000      0.000000
max       90.000000      16.000000       99.000000  99999.000000

In [98]:
#2.2.6
dataframe.iloc[1:4]

age         workclass  education_num      marital_status  \
1   50  Self-emp-not-inc             13  Married-civ-spouse   
2   38           Private              9            Divorced   
3   53           Private              7  Married-civ-spouse   

          occupation   relationship   race gender  hours_per_week  \
1    Exec-managerial        Husband  White   Male              13   
2  Handlers-cleaners  Not-in-family  White   Male              40   
3  Handlers-cleaners        Husband  Other   Male              40   

  native_country  capital income_status  
1  United-States        0         <=50K  
2  United-States        0         <=50K  
3  United-States        0         <=50K

In [99]:
dataframe[dataframe['age'] == 33].head(2)

age workclass  education_num      marital_status       occupation  \
80    33   Private             14  Married-civ-spouse   Prof-specialty   
141   33   Private             13       Never-married  Exec-managerial   

       relationship   race  gender  hours_per_week native_country  capital  \
80          Husband  White    Male              50  United-States        0   
141  Other-relative  Other  Female              40          Other        0   

    income_status  
80          <=50K  
141         <=50K

## 3.1. Теоретический материал – Работа с числовыми данными
Количественные данные что-то измеряют – будь то размер класса, ежемесячные продажи или оценки учащихся. Естественным способом представления этих величин является численным (например, 150 студентов, $529 392 продаж).
  
**Нормализация данных** — это общепринятая задача предобработки в машинном обучении. Многие алгоритмы предполагают, что все признаки находятся в единой шкале, как правило, от 0 до 1 или от -1 до 1.
   
Существует множество способов нормализации значений признаков, чтобы масштабировать их к единому диапазону и использовать в различных моделях машинного обучения. В зависимости от используемой функции, их можно разделить на 2 большие группы: линейные и нелинейные. При
нелинейной нормализации в расчетных соотношениях используются функции логистической сигмоиды или гиперболического тангенса. В линейной нормализации изменение переменных осуществляется пропорционально, по линейному закону.
  
На практике наиболее распространены следующие методы нормализации признаков:
- **Минимакс** – линейное преобразование данных в диапазоне [0..1], где минимальное и максимальное масштабируемые значения соответствуют 0 и 1 соответственно;
- **Z-масштабирование** данных на основе среднего значения и стандартного отклонения: производят деление разницы между переменной и средним значением на стандартное отклонение.

$$X_{norm} = \frac{X - X_{min}}{X_{max} - X_{min}}$$
<p style="text-align: center;">Нормализация по методу минимакс</p>
  
$$z = \frac{x - \mu}{\sigma}$$
<p style="text-align: center;">Z-масштабирование</p>

При масштабировании данных мы будем использовать одну из популярных библиотек машинного обучения *Scikit-learn*. Библиотека содержит пакет sklearn.preprocessing, который предоставляет широкие возможности для нормализации данных. Следует отметить, что в целом алгоритмы обучения выигрывают от стандартизации набора данных.

### 3.2.1. Пример
#### Задача: прошкалируйте числовой признак в диапазон между двумя значениями

In [100]:
# Загрузить библиотеки
import numpy as np
from sklearn import preprocessing

# Создать признак
feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])
# Создать шкалировщик
minmax_scale = preprocessing.MinMaxScaler(feature_range = (0, 1))

# Прошкалировать признак
scaled_feature = minmax_scale.fit_transform(feature)

# Покказать прошкалированный признак
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

### 3.2.2. Пример
#### Задача: преобразуйте признак, чтобы он имел среднее значение 0 и стандартное отклонение 1

Мы можем увидеть эффект стандартизации, обратившись к среднему значению и стандартному отклонению результата нашего решения

In [101]:
x = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])
# Создать шкалировщик
scaler = preprocessing.StandardScaler()
# Преобразовать признак
standardized = scaler.fit_transform(x)
# Показать признак
standardized

print("Среднее:", round(standardized.mean()))
print("Стандартное отклонение:", standardized.std())

Среднее: 0
Стандартное отклонение: 1.0


### 3.2.3. Пример
#### Задача: дан фрейм данных. Необходимо масштабировать его числовые столбцы.
```python
dfTest = pd.DataFrame({'A':[14.00, 90.20, 90.95, 96.27, 91.21],
                       'B':[103.02, 107.26, 110.35, 114.23, 114.68],
                       'C':['big', 'small', 'big', 'small', 'small']})
```

In [102]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
dfTest = pd.DataFrame({'A':[14.00, 90.20, 90.95, 96.27, 91.21],
                       'B':[103.02, 107.26, 110.35, 114.23, 114.68],
                       'C':['big', 'small', 'big', 'small', 'small']})

dfTest[['A', 'B']] = scaler.fit_transform(dfTest[['A', 'B']])
dfTest

A         B      C
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small

### 3.3.2 Задание
#### Задача: Загрузить фрейм данных по ссылке: https://raw.githubusercontent.com/akmand/datasets/master/iris.csv. Необходимо выполнить нормализацию первого числового признака (sepal_length_cm) с использованием минимаксного преобразования, а второго (sepal_width_cm) с задействованием z-масштабирования.

In [2]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler

# Загрузка данных
url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
data = pd.read_csv(url)

min_max_scaler = MinMaxScaler()
standard_scaler = StandardScaler()

# Нормализуем первый признак (sepal_length_cm) с использованием минимаксного преобразования
data['sepal_length_cm_normalized'] = min_max_scaler.fit_transform(data[['sepal_length_cm']])

# Нормализуем второй признак (sepal_width_cm) с использованием z-масштабирования
data['sepal_width_cm_normalized'] = standard_scaler.fit_transform(data[['sepal_width_cm']])

print(data.head())

   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species  \
0              5.1             3.5              1.4             0.2  setosa   
1              4.9             3.0              1.4             0.2  setosa   
2              4.7             3.2              1.3             0.2  setosa   
3              4.6             3.1              1.5             0.2  setosa   
4              5.0             3.6              1.4             0.2  setosa   

   sepal_length_cm_normalized  sepal_width_cm_normalized  
0                    0.222222                   1.032057  
1                    0.166667                  -0.124958  
2                    0.111111                   0.337848  
3                    0.083333                   0.106445  
4                    0.194444                   1.263460  
